version: 2
jobs:
  build:
    docker:
      - image: 9.6.9-alpine

    steps:
      - checkout

      - run:
          name: Greeting
          command: |
            apk add bash curl-dev
            echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
